src/main/java/com/sejel/monitor/business/beans/MonitorSettingsBean.java
package com.sejel.monitor.business.beans;

import com.sejel.monitor.business.parentBeans.AbstractFacadeWrapper;
import com.sejel.monitor.persistence.entity.AmGroups;
import com.sejel.monitor.persistence.entity.AmKpiType;
import com.sejel.monitor.persistence.entity.AmKpis;
import com.sejel.monitor.persistence.entity.AmSystems;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Stateless
public class MonitorSettingsBean extends AbstractFacadeWrapper<AmSystems> {
    @PersistenceContext(unitName = "MainUnit")
    private EntityManager em;

    public MonitorSettingsBean() {
        super(AmSystems.class);
    }

    public List<AmSystems> getAllAmSystems(){
        try{
            return em.createQuery("select s from AmSystems s", AmSystems.class).getResultList();
        }catch (Exception e){
            return new ArrayList<>();
        }
    }
    public List<AmGroups> getAllAmGroups(){
        try{
            return em.createQuery("select s from AmGroups s", AmGroups.class).getResultList();
        }catch (Exception e){
            return new ArrayList<>();
        }
    }
    public List<AmKpis> getAllAmKpis(){
        try{
            return em.createQuery("select s from AmKpis s", AmKpis.class).getResultList();
        }catch (Exception e){
            return new ArrayList<>();
        }
    }


    public void addSystem(AmSystems system){

        if(system.getSysId()==null){
            system.setSysId((Long) em.createNativeQuery(system.getSequenceIdQuery()).getSingleResult());
        }
        system.setCreateTimestamp(new Date());
        system.setSysEventsCount(0);
        system.setSysState(0);
        em.merge(system);
    }

    public void addGroup(AmGroups grp){

        if(grp.getGrpId()==null){
            grp.setGrpId((Long) em.createNativeQuery(grp.getSequenceIdQuery()).getSingleResult());
        }
        grp.setCreateTimestamp(new Date());
        grp.setGrpEventsCount(0);
        grp.setGrpState(0);
        em.merge(grp);
    }

    public void addKpi(AmKpis kpi){

        if(kpi.getKpiId()==null){
            kpi.setKpiId((Long) em.createNativeQuery(kpi.getSequenceIdQuery()).getSingleResult());
        }
        kpi.setKpiLastRefreshTimestamp(new Date());
        kpi.setCreateTimestamp(new Date());
        kpi.setKpiEventsCount(0);
        kpi.setKpiState(0);
        em.merge(kpi);
    }

    public void changeSystemState(AmSystems sys){
        if(sys.getSysState() == 0){
            sys.setSysState(512);
            em.merge(sys);
        }else{
            sys.setSysState(0);
            em.merge(sys);
        }
    }

    public void changeGroupState(AmGroups grp){
        if(grp.getGrpState() == 0){
            grp.setGrpState(512);
            em.merge(grp);
        }else{
            grp.setGrpState(0);
            em.merge(grp);
        }
    }

    public void changeKpiState(AmKpis kpi){
        if(kpi.getKpiState() == 0){
            kpi.setKpiState(512);
            em.merge(kpi);
        }else{
            kpi.setKpiState(0);
            em.merge(kpi);
        }
    }

    public List<AmKpiType> getKpiTypes(){
        return em.createQuery("select s from AmKpiType s",AmKpiType.class).getResultList();
    }

}

src/main/webapp/pages/Settings/ApplicationSettings.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template.xhtml">
    <ui:define name="breadcrumb">
        <li>
            <p:link>#{localeResources['sidebar.settings']} / #{localeResources['sidebar.app.settings']}</p:link>
        </li>
    </ui:define>

    <ui:define name="content">
        <div class="ui-g">
            <div class="ui-g-12">
                <h3>#{localeResources['sidebar.app.settings']}</h3>
                <p:messages closable="true" globalOnly="true"/>

                <h:form id="addGroup" prependId="false" rendered="#{request.isUserInRole('App Monitor Settings')}">
                    <div class="tealcard card-w-title">
                        <h3>#{localeResources['monitor.group']}</h3>
                        <p:panel header="#{localeResources['add.new']} #{localeResources['monitor.group']}">

                            <p:panelGrid columns="2" layout="grid" styleClass="ui-panelgrid-blank form-group">

                                <h:panelGroup styleClass="md-inputfield">
                                    <p:inputText id="grpName" style="width: 100%"
                                                 value="#{monitorSettingsController.newGroup.grpName}"
                                                 requiredMessage="#{localeResources['system.input.required']}"
                                                 required="true" maxlength="50"/>
                                    <label>#{localeResources['monitor.group.name']}</label>
                                    <p:message for="grpName" display="text"/>
                                </h:panelGroup>

                                <h:panelGroup styleClass="md-inputfield">
                                    <p:selectOneMenu id="sysList" filter="true" filterMatchMode="contains"
                                                     value="#{monitorSettingsController.newGroup.grpSysId}"
                                                     required="true"
                                                     requiredMessage="#{localeResources['system.input.required']}">
                                        <f:selectItem itemLabel="" itemValue=""/>
                                        <f:selectItems value="#{monitorSettingsController.systemsList}" var="sysLists"
                                                       itemLabel="#{sysLists.sysName}" itemValue="#{sysLists.sysId}"/>
                                    </p:selectOneMenu>
                                    <label>#{localeResources['monitor.group.related.system']} </label>
                                    <p:message for="sysList" display="text"/>
                                </h:panelGroup>

                            </p:panelGrid>

                            <div style="float:#{localeResources.lang eq 'ar' ? 'left':'right'}">
                                <p:commandButton value="#{localeResources['System.action.Save']}"
                                                 ajax="false"
                                                 action="#{monitorSettingsController.addGroup()}"
                                                 styleClass="teal-btn"/>

                                <p:spacer width="10"/>

                                <p:commandButton value="#{localeResources['system.button.cancel']}"
                                                 ajax="false" immediate="true"
                                                 action="#{monitorSettingsController.cancel()}"
                                                 styleClass="teal-btn"/>
                            </div>
                            <br/>
                            <br/>
                        </p:panel>

                        <br/><p:fragment/>


                        <p:dataTable value="#{monitorSettingsController.groupsList}" var="grp" lazy="false" sortBy="#{grp.grpId}"
                                     currentPageReportTemplate="#{localeResources['General.Pagination.totalOfRows']} : {totalRecords}    #{localeResources['General.pagination.showing']} {currentPage} #{localeResources['General.pagination.of']} {totalPages} #{localeResources['General.pagination.pages']}"
                                     emptyMessage="#{localeResources['System.tables.noData']}" rows="10" id="groupTable">


                        <p:column headerText="#{localeResources['id']}" filterMatchMode="contains" filterBy="#{grp.grpId}" sortBy="#{grp.grpId}">
                                <h:outputText value="#{grp.grpId}"/>
                            </p:column>

                            <p:column headerText="#{localeResources['monitor.group.name']}" filterMatchMode="contains" filterBy="#{grp.grpName}" sortBy="#{grp.grpName}">
                                <h:outputText value="#{grp.grpName}"/>
                            </p:column>

                            <p:column headerText="#{localeResources['monitor.group.related.system']}" filterMatchMode="contains" filterBy="#{grp.grpSysId}" sortBy="#{grp.grpSysId}">
                                <h:outputText value="#{grp.grpSysId} - #{grp.system.sysName}"/>
                            </p:column>

                            <p:column headerText="#{localeResources['action.by']}" filterMatchMode="contains" filterBy="#{grp.changeUsername}" sortBy="#{grp.changeUsername}">
                                <h:outputText value="#{grp.changeUsername}"/>
                            </p:column>

                            <p:column headerText="#{localeResources['status']}" filterMatchMode="contains" filterBy="#{grp.grpState}" sortBy="#{grp.grpState}">
                            <h:outputText value="#{grp.grpState eq 0 ? localeResources['system.generic.active']:localeResources['system.generic.deactive']}"
                                          styleClass="#{grp.grpState eq 0 ? 'Approved':'Rejected'}"/>
                            </p:column>


                            <p:column>
                                <p:menuButton value="#{localeResources['system.generic.actions']}">
                                    <p:menuitem value="#{localeResources['system.generic.actions.edit']}"
                                                immediate="true" ajax="false"
                                                action="#{monitorSettingsController.editGroup(grp)}"
                                                icon="ui-icon-edit"/>

                                    <p:menuitem value="#{grp.grpState eq 0? localeResources['system.generic.Deactivate'] : localeResources['system.generic.Activate']}"
                                                immediate="true" ajax="false"
                                                action="#{monitorSettingsController.changeGroupState(grp)}"
                                                icon="#{grp.grpState eq 0? 'ui-icon-close':'ui-icon-check'}"/>
                                </p:menuButton>
                            </p:column>


                        </p:dataTable>

                    </div>
                </h:form>

            </div>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/pages/Settings/GroupsSettings.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template.xhtml">
    <ui:define name="breadcrumb">
        <li>
            <p:link>#{localeResources['sidebar.settings']} / #{localeResources['monitor.group.settings']}</p:link>
        </li>
    </ui:define>

    <ui:define name="content">
        <div class="ui-g">
            <div class="ui-g-12">
                <h3>#{localeResources['monitor.group.settings']}</h3>
                <p:messages closable="true" globalOnly="true"/>

                <h:form id="addGroup" prependId="false" rendered="#{request.isUserInRole('App Monitor Settings')}">
                    <div class="tealcard card-w-title">

                        <p:panel header="#{localeResources['add.new']} #{localeResources['monitor.group']}">

                            <p:panelGrid columns="2" layout="grid" styleClass="ui-panelgrid-blank form-group">

                                <h:panelGroup styleClass="md-inputfield">
                                    <p:inputText id="grpName" style="width: 100%"
                                                 value="#{monitorSettingsController.newGroup.grpName}"
                                                 requiredMessage="#{localeResources['system.input.required']}"
                                                 required="true" maxlength="50"/>
                                    <label>#{localeResources['monitor.group.name']}</label>
                                    <p:message for="grpName" display="text"/>
                                </h:panelGroup>

                                <h:panelGroup styleClass="md-inputfield">
                                    <p:selectOneMenu id="sysList" filter="true" filterMatchMode="contains"
                                                     value="#{monitorSettingsController.newGroup.grpSysId}"
                                                     required="true"
                                                     requiredMessage="#{localeResources['system.input.required']}">
                                        <f:selectItem itemLabel="" itemValue=""/>
                                        <f:selectItems value="#{monitorSettingsController.systemsList}" var="sysLists"
                                                       itemLabel="#{sysLists.sysName}" itemValue="#{sysLists.sysId}"/>
                                    </p:selectOneMenu>
                                    <label>#{localeResources['monitor.group.related.system']} </label>
                                    <p:message for="sysList" display="text"/>
                                </h:panelGroup>

                            </p:panelGrid>

                            <div style="float:#{localeResources.lang eq 'ar' ? 'left':'right'}">
                                <p:commandButton value="#{localeResources['System.action.Save']}"
                                                 ajax="false"
                                                 action="#{monitorSettingsController.addGroup()}"
                                                 styleClass="teal-btn"/>

                                <p:spacer width="10"/>

                                <p:commandButton value="#{localeResources['system.button.cancel']}"
                                                 ajax="false" immediate="true"
                                                 action="#{monitorSettingsController.cancel('GroupsSettings')}"
                                                 styleClass="teal-btn"/>
                            </div>
                            <br/>
                            <br/>
                        </p:panel>

                        <br/><p:fragment/>


                        <p:dataTable value="#{monitorSettingsController.groupsList}" var="grp" lazy="false"
                                     sortBy="#{grp.grpId}"
                                     currentPageReportTemplate="#{localeResources['General.Pagination.totalOfRows']} : {totalRecords}    #{localeResources['General.pagination.showing']} {currentPage} #{localeResources['General.pagination.of']} {totalPages} #{localeResources['General.pagination.pages']}"
                                     emptyMessage="#{localeResources['System.tables.noData']}" rows="10"
                                     id="groupTable">


                            <p:column headerText="#{localeResources['id']}" filterMatchMode="contains"
                                      filterBy="#{grp.grpId}" sortBy="#{grp.grpId}">
                                <h:outputText value="#{grp.grpId}"/>
                            </p:column>

                            <p:column headerText="#{localeResources['monitor.group.name']}" filterMatchMode="contains"
                                      filterBy="#{grp.grpName}" sortBy="#{grp.grpName}">
                                <h:outputText value="#{grp.grpName}"/>
                            </p:column>

                            <p:column headerText="#{localeResources['monitor.group.related.system']}"
                                      filterMatchMode="contains" filterBy="#{grp.grpSysId}" sortBy="#{grp.grpSysId}">
                                <h:outputText value="#{grp.grpSysId} - #{grp.system.sysName}"/>
                            </p:column>

                            <p:column headerText="#{localeResources['action.by']}" filterMatchMode="contains"
                                      filterBy="#{grp.changeUsername}" sortBy="#{grp.changeUsername}">
                                <h:outputText value="#{grp.changeUsername}"/>
                            </p:column>

                            <p:column headerText="#{localeResources['status']}" filterMatchMode="contains"
                                      filterBy="#{grp.grpState}" sortBy="#{grp.grpState}">
                                <h:outputText
                                        value="#{grp.grpState eq 0 ? localeResources['system.generic.active']:localeResources['system.generic.deactive']}"
                                        styleClass="#{grp.grpState eq 0 ? 'Approved':'Rejected'}"/>
                            </p:column>


                            <p:column>
                                <p:menuButton value="#{localeResources['system.generic.actions']}">
                                    <p:menuitem value="#{localeResources['system.generic.actions.edit']}"
                                                immediate="true" ajax="false"
                                                action="#{monitorSettingsController.editGroup(grp)}"
                                                icon="ui-icon-edit"/>

                                    <p:menuitem
                                            value="#{grp.grpState eq 0? localeResources['system.generic.Deactivate'] : localeResources['system.generic.Activate']}"
                                            immediate="true" ajax="false"
                                            action="#{monitorSettingsController.changeGroupState(grp)}"
                                            icon="#{grp.grpState eq 0? 'ui-icon-close':'ui-icon-check'}"/>
                                </p:menuButton>
                            </p:column>


                        </p:dataTable>

                    </div>
                </h:form>

            </div>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/pages/Settings/KpisSettings.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template.xhtml">
    <ui:define name="breadcrumb">
        <li>
            <p:link>#{localeResources['sidebar.settings']} / #{localeResources['monitor.kpi.settings']}</p:link>
        </li>
    </ui:define>

    <ui:define name="content">
        <div class="ui-g">
            <div class="ui-g-12">
                <h3>#{localeResources['monitor.kpi.settings']}</h3>
                <p:messages closable="true" globalOnly="true"/>

                <h:form id="addKpi" prependId="false" rendered="#{request.isUserInRole('App Monitor Settings')}">
                    <div class="tealcard card-w-title">

                        <p:panel header="#{localeResources['add.new']} #{localeResources['monitor.kpi']}">

                            <p:panelGrid columns="2" layout="grid" styleClass="ui-panelgrid-blank form-group">

                                <h:panelGroup styleClass="md-inputfield">
                                    <p:inputText id="kpiName" style="width: 100%"
                                                 value="#{monitorSettingsController.newKpi.kpiName}"
                                                 requiredMessage="#{localeResources['system.input.required']}"
                                                 required="true" maxlength="50"/>
                                    <label>#{localeResources['monitor.kpi.name']}</label>
                                    <p:message for="kpiName" display="text"/>
                                </h:panelGroup>

                                <h:panelGroup styleClass="md-inputfield">
                                    <p:selectOneMenu id="grpList" filter="true" filterMatchMode="contains"
                                                     value="#{monitorSettingsController.newKpi.kpiGrpId}"
                                                     required="true"
                                                     requiredMessage="#{localeResources['system.input.required']}">
                                        <f:selectItem itemLabel="" itemValue=""/>
                                        <f:selectItems value="#{monitorSettingsController.groupsList}" var="grpLists"
                                                       itemLabel="#{grpLists.system.sysName} - #{grpLists.grpName}"
                                                       itemValue="#{grpLists.grpId}"/>
                                    </p:selectOneMenu>
                                    <label>#{localeResources['monitor.kpi.related.group']} </label>
                                    <p:message for="grpList" display="text"/>
                                </h:panelGroup>

                                <h:panelGroup styleClass="md-inputfield">
                                    <p:selectOneMenu id="kpiTyeps"
                                                     value="#{monitorSettingsController.newKpi.kpiTypeId}"
                                                     required="true"
                                                     requiredMessage="#{localeResources['system.input.required']}">
                                        <f:selectItem itemLabel="" itemValue=""/>
                                        <f:selectItems value="#{monitorSettingsController.kpiTypes}" var="kpiTypesVar"
                                                       itemLabel="#{kpiTypesVar.kpiTypeName}"
                                                       itemValue="#{kpiTypesVar.kpiTypeId}"/>
                                    </p:selectOneMenu>
                                    <label>#{localeResources['monitor.kpi.type']} </label>
                                    <p:message for="kpiTyeps" display="text"/>
                                </h:panelGroup>

                                <h:panelGroup styleClass="md-inputfield">
                                    <p:inputText id="refreshTime" style="width: 100%"
                                                 value="#{monitorSettingsController.newKpi.kpiRefreshTimeMins}"
                                                 onkeyup="$(this).val($(this).val().replace(/[^0-9]/g, ''));"
                                                 requiredMessage="#{localeResources['system.input.required']}"
                                                 required="true" maxlength="4"/>
                                    <label>#{localeResources['monitor.kpi.refresh.min']}</label>
                                    <p:message for="refreshTime" display="text"/>
                                </h:panelGroup>

                            </p:panelGrid>

                            <p:panelGrid columns="1" layout="grid" styleClass="ui-panelgrid-blank form-group">
                                <h:panelGroup styleClass="md-inputfield">
                                    <p:inputText id="kpiCheckQuery" style="width: 100%"
                                                 value="#{monitorSettingsController.newKpi.kpiCheckQuery}"
                                                 requiredMessage="#{localeResources['system.input.required']}"
                                                 required="true"/>
                                    <label>#{localeResources['monitor.kpi.check.query']}</label>
                                    <p:message for="kpiCheckQuery" display="text"/>
                                </h:panelGroup>
                                <h:panelGroup styleClass="md-inputfield">
                                    <p:inputText id="kpiResultQuery" style="width: 100%"
                                                 value="#{monitorSettingsController.newKpi.kpiResultQuery}"
                                                 requiredMessage="#{localeResources['system.input.required']}"
                                                 required="true"/>
                                    <label>#{localeResources['monitor.kpi.result.query']}</label>
                                    <p:message for="kpiResultQuery" display="text"/>
                                </h:panelGroup>
                                <h:panelGroup styleClass="md-inputfield">
                                    <p:inputText id="columnsTemplate" style="width: 100%"
                                                 value="#{monitorSettingsController.newKpi.columnsTemplate}"
                                                 requiredMessage="#{localeResources['system.input.required']}"
                                                 required="true"/>
                                    <label>#{localeResources['monitor.kpi.columns.template']}</label>
                                    <p:message for="columnsTemplate" display="text"/>
                                </h:panelGroup>
                            </p:panelGrid>

                            <div style="float:#{localeResources.lang eq 'ar' ? 'left':'right'}">
                                <p:commandButton value="#{localeResources['System.action.Save']}"
                                                 ajax="false"
                                                 action="#{monitorSettingsController.addKpi()}"
                                                 styleClass="teal-btn"/>

                                <p:spacer width="10"/>

                                <p:commandButton value="#{localeResources['system.button.cancel']}"
                                                 ajax="false" immediate="true"
                                                 action="#{monitorSettingsController.cancel('KpisSettings')}"
                                                 styleClass="teal-btn"/>
                            </div>
                            <br/>
                            <br/>
                        </p:panel>

                        <br/><p:fragment/>


                        <p:dataTable value="#{monitorSettingsController.kpisList}" var="kpi" lazy="false"
                                     sortBy="#{kpi.kpiId}"
                                     currentPageReportTemplate="#{localeResources['General.Pagination.totalOfRows']} : {totalRecords}    #{localeResources['General.pagination.showing']} {currentPage} #{localeResources['General.pagination.of']} {totalPages} #{localeResources['General.pagination.pages']}"
                                     emptyMessage="#{localeResources['System.tables.noData']}" rows="10" id="kpiTable">


                            <p:column headerText="#{localeResources['id']}" filterMatchMode="contains"
                                      filterBy="#{kpi.kpiId}" sortBy="#{kpi.kpiId}">
                                <h:outputText value="#{kpi.kpiId}"/>
                            </p:column>

                            <p:column headerText="#{localeResources['monitor.kpi.name']}" filterMatchMode="contains"
                                      filterBy="#{kpi.kpiName}" sortBy="#{kpi.kpiName}">
                                <h:outputText value="#{kpi.kpiName}"/>
                            </p:column>

                            <p:column headerText="#{localeResources['monitor.kpi.related.group']}"
                                      filterMatchMode="contains" filterBy="#{kpi.kpiGrpId}" sortBy="#{kpi.kpiGrpId}">
                                <h:outputText value="#{kpi.kpiGrpId} - #{kpi.group.grpName}"/>
                            </p:column>

                            <p:column headerText="#{localeResources['monitor.kpi.type']}" filterMatchMode="contains"
                                      filterBy="#{kpi.kpiTypeId}" sortBy="#{kpi.kpiTypeId}">
                                <h:outputText value="#{kpi.kpiTypeId} - #{kpi.kpiType.kpiTypeName}"/>
                            </p:column>

                            <p:column headerText="#{localeResources['action.by']}" filterMatchMode="contains"
                                      filterBy="#{kpi.changeUsername}" sortBy="#{kpi.changeUsername}">
                                <h:outputText value="#{kpi.changeUsername}"/>
                            </p:column>

                            <p:column headerText="#{localeResources['status']}" filterMatchMode="contains"
                                      filterBy="#{kpi.kpiState}" sortBy="#{kpi.kpiState}">
                                <h:outputText
                                        value="#{kpi.kpiState eq 0 ? localeResources['system.generic.active']:localeResources['system.generic.deactive']}"
                                        styleClass="#{kpi.kpiState eq 0 ? 'Approved':'Rejected'}"/>
                            </p:column>


                            <p:column>
                                <p:menuButton value="#{localeResources['system.generic.actions']}">
                                    <p:menuitem value="#{localeResources['system.generic.actions.edit']}"
                                                immediate="true" ajax="false"
                                                action="#{monitorSettingsController.editKpi(kpi)}"
                                                icon="ui-icon-edit"/>

                                    <p:menuitem
                                            value="#{kpi.kpiState eq 0? localeResources['system.generic.Deactivate'] : localeResources['system.generic.Activate']}"
                                            immediate="true" ajax="false"
                                            action="#{monitorSettingsController.changeKpiState(kpi)}"
                                            icon="#{kpi.kpiState eq 0? 'ui-icon-close':'ui-icon-check'}"/>
                                </p:menuButton>
                            </p:column>


                        </p:dataTable>

                    </div>
                </h:form>


            </div>
        </div>
    </ui:define>
</ui:composition>